[master]
name            = "NS2 Optimizations"
description     = "README.md"
autodescription = true
tags            = ["Must be run on Server"]
preview         = "preview.jpg"
website         = "https://github.com/woozasmoddingteam/NS2-Optimizations/"

[beta]
name            = "NS2 Optimizations - Beta"
description     = "description.beta.txt"
autodescription = false
tags            = ["Must be run on Server"]
preview         = "preview.jpg"
